### ISSUE TITLE
Unordered list styling

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/getkong.org#1]
In FirefoxDeveloperEdition the list item text gets pushed below the bullet point:

![screen shot 2015-03-24 at 5 28 53 pm](https://cloud.githubusercontent.com/assets/24260/6816056/5e5fd18a-d24b-11e4-9126-654bca09616d.png)

**Comment by ahmadnassri** [comment]
this seems to be not applicable anymore? old site design?
