### ISSUE TITLE
Meetup area update.

### ISSUE THREAD

**Issue by sinzone** [Mashape/getkong.org#103]
http://www.meetup.com/meetup_api/buttons/

**Comment by ahmadnassri** [comment]
- [ ] programatically grab the next event meetup link

**Comment by sinzone** [comment]
actually now that we have kong.meetup.com we need to put that under Meetup section:

"Join the Kong community near you or create a new meetup with "kong" as a topic:

![] (http://cl.ly/image/1L1y1n2R2u10/Image%202015-07-24%20at%2012.31.32%20PM.png)

**Comment by ahmadnassri** [comment]
open a separate issue plz, this one is about the RSVP button

**Comment by ahmadnassri** [comment]
can close this if [meetup-map](https://github.com/Mashape/getkong.org/tree/meetup-map) branch is merged
