### ISSUE TITLE
[guide] Kong development (plugins + core)

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/getkong.org#107]
- How to install Kong for development
- How to develop a plugin for Kong
- How to develop on Kong's core. What is the philosophy of Kong-core and how is it organized?

**Comment by sinzone** [comment]
we should do this, only once we pushed out plugins from the core.

**Comment by orliesaurus** [comment]
+1

**Comment by gazsp** [comment]
+1 I'm also interested in Kong from a plug-in development point of view

**Comment by sinzone** [comment]
@gazsp in the meantime: http://streamdata.io/blog/developing-an-helloworld-kong-plugin/

**Comment by gazsp** [comment]
Thanks!

**Comment by thibaultCha** [comment]
(Written and deployed)
