### ISSUE TITLE
Cannot view entire documentation sidebar

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/getkong.org#108]
Running Chromium on Ubuntu 15.10 I can't access the bottom of the sidebar. It fixes into position and doesn't have it's own scroll bar making the bottom overflow into the bottom of my screen. The only way to see it is by scrolling to the bottom of the page which then removes `position: fixed`

**Comment by sinzone** [comment]
the problem was that when you are on API REF you scroll down and you don't know where you are at. since you lost the sidebar. and then you have to scroll up forever. so either make api ref attached to header or either put "scroll up" link bottom right to jump back to the top.

**Comment by thibaultCha** [comment]
For now we removed the fixed position so that there is no this issue. When we'll switch to some real API documentation we'll be able to have nice doc that scales.
