### ISSUE TITLE
docs.html layout should be versioned

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/getkong.org#12]
[_layouts/docs.html](https://github.com/Mashape/getkong.org/blob/master/app/_layouts/docs.html) is what is on the left side of a documentation page. Not every version to document will have the same articles (in fact, the 2 versions we currently have already differ, resulting in a few 404s), and in the future there might be a lot more to it.

To dynamically generate it, we can either have a list of all articles in [kong_versions.yml](https://github.com/Mashape/getkong.org/blob/master/app/_data/kong_versions.yml), or we could dynamically generate that list via the [versions.rb](https://github.com/Mashape/getkong.org/blob/master/app/_jekyll_plugins/versions.rb) plugin. One is more flexible, the other is less to maintain.

Then `docs.html` simply becomes:

```html
<aside class="page-navigation">
  {% for section in page.doc_link %}
  <nav>
    <h5>{{section.title}}</h5>
    <ul>
      {% for article in section.articles %}
        <li href="/docs/{{page.kong_version}}/{{article.link}}">{{article.name}}</li>
      {% endfor %}      
    </ul>
  </nav>
  {% endfor %}
</aside>
```

Which solution do we like better: YAML or automated?

**Comment by thibaultCha** [comment]
@ahmadnassri @montanaflynn @thefosk @Nijikokun

**Comment by ahmadnassri** [comment]
best to keep in `kong_versions.yml`

reasons:

1. we limit to "supported" versions only (think enterprise LTS)
2. jekyll plugins make updating the site manual, whereas you can just leave it for gh-pages

**Comment by Nijikokun** [comment]
> jekyll plugins make updating the site manual, whereas you can just leave it for gh-pages

could just build on travis

**Comment by ahmadnassri** [comment]
> its already manual...

if that's the case already, then no change, other point still stands to greater value I think

**Comment by Nijikokun** [comment]
> if that's the case already, then no change, other point still stands to greater value I think

We could have have a list of "non-supported" versions for that, easier to maintain that list than a list of every version **plus** their pages.

**Comment by ahmadnassri** [comment]
> We could have have a list of "non-supported" versions for that, easier to maintain that list than a list of every version plus their pages.

wouldn't you just want to publish ONLY the supported pages on the website? 

scenario:
when people bookmark an old version docs url, they come back and its 404, which is *good* as that's feedback for them to know its no longer supported, and start looking at new docs, realize update is needed.

**Comment by Nijikokun** [comment]
I think I am missing what your "*other point*" was then, I was assuming you meant supporting specific versions.

In my model originally it was just supported versions, I was going on assuming that you wanted both supported / non-supported. My mistake. Can you clarify what your "*other point*" is?

**Comment by ahmadnassri** [comment]
other point:

> we limit to "supported" versions only (think enterprise LTS)
> - which would be a manual/human decision to decide anyways

so we're saying the same thing :) 

:hand:

**Comment by ahmadnassri** [comment]
to be exact:

- *do* delete old docs versions so they are not accessible on the web (even if not linked)
- use a versions file, or Jekyll collections or plugins or anything to automatically list versions, avoid manual work.

**Comment by Nijikokun** [comment]
Yes, I think a plugin is the best suited for this or a part of the gulp deploy / build process that currently exists.

- Iterates over list of folders (obtains version number)
- Creates `kong_versions.yml` with list of pages for *each* version (sidebar support)
- Associates `latest:` configuration yaml value to handle with redirects for #13

Automated :+1:

**Comment by thibaultCha** [comment]
@ahmadnassri 

> if people want access to older docs, then they use git history.

Wait, are you saying we are currently versioning the docs for nothing?

**Comment by thibaultCha** [comment]
> keep only supported versions

I see. Well, I wanted to delete the beta docs once `0.2.0` (public release) is released, so, yeah, I guess we are on the same page.

**Comment by thibaultCha** [comment]
Ok @Nijikokun , what you described is what `versions.rb` is doing (detecting version, detecting latest from `_data/versions.yml` (which could also contain some meta infos per release), so we're all good. Then it'll be automated. 

A detail: the sidebar only supports 2 nested levels because of the UI

**Comment by Nijikokun** [comment]
> A detail: the sidebar only supports 2 nested levels because of the UI

Yaml supports nesting

**Comment by thibaultCha** [comment]
Of course, I'm saying the UI doesn't.

**Comment by rainum** [comment]
@thibaultCha you can nest level as deep as you want. Maybe it not very beautiful, but it works 

![nesting](https://cloud.githubusercontent.com/assets/846796/7533638/d4e9b2a0-f57b-11e4-8b1d-4716c4161559.png)

**Comment by thibaultCha** [comment]
That was not the issue here. The issue is a reminder that we will need a versioned menu one day as soon as one version will have a new section. Having this being nested is nice and might allow use one of the solutions I proposed to fix this issue. Or maybe we'll use another solution, I don't know, but this is not closed.

**Comment by rainum** [comment]
Documentation will have url like http://getkong.org/docs/{latest_version}. This URL pattern is more convenient and understandable because all docs URLs is like http://getkong.org/docs/{latest_version}/about/plugins/. To avoid problem with 404 on /docs URL I've modified ruby script, so now if you'll go to /docs you'll be redirected to /docs/{latest_version}.

To add new docs version you need to add version to [kong_versions.yml](https://github.com/Mashape/getkong.org/blob/master/app/_data/kong_versions.yml) and create similar to [this folder](https://github.com/Mashape/getkong.org/tree/master/app/docs/0.2.0-2) folder with appropriate to version name. Thats it. Latest version for Jekyll will be last item in [kong_versions.yml](https://github.com/Mashape/getkong.org/blob/master/app/_data/kong_versions.yml).

**Comment by rainum** [comment]
Dropdown for docs version selection is on the way

**Comment by ahmadnassri** [comment]
can we close this now?

**Comment by rainum** [comment]
I think we can, @thibaultCha @Nijikokun ?

**Comment by thibaultCha** [comment]
No it's still not done? 0.3.0 will actually break it.

**Comment by thefosk** [comment]
@rainum work full-time on this

**Comment by thibaultCha** [comment]
The issue is that now 0.3.0 will have a new API documentation, and changing the current `docs.html` will break all the old versions of the docs. This is the exact use case this issue was trying to warn about. So now we have to find a way to separate the content of the sidebar on a per-version basis

**Comment by rainum** [comment]
@thefosk I don't know what structure will new docs have. So It would be better if we talk about this issue, when new docs will be ready.

**Comment by thibaultCha** [comment]
We won't have time, this needs to be out before we release 0.3.0. It'll be basically the same structure except with a few more/less API routes.

**Comment by rainum** [comment]
Okay, we can move menu items to separate file (.yml or .json) as it was in first page version. Today I have a lot of work with new analytics website, so I'll switch to Kong tomorrow, if you guys don't mind.

**Comment by thefosk** [comment]
@rainum work full time on Kong - release it tomorrow.

**Comment by rainum** [comment]
I've added versioning for docs navigation. You need to simply create .yml file in `app/_data/` with version name in filename `docs_nav_%version%.yml`, like `app/_data/docs_nav_0.2.1.yml`.

Please check it yourself and close an issue if all is ok, @thefosk @thibaultCha
