### ISSUE TITLE
Setup redirects to the latest docs version

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/getkong.org#13]
As mentioned in #10, we should redirect a request at `/docs/{latest,current}` to `/docs/x.x.x. This can only happen if we host getkong.org somewhere else of if we use something such as cloudflare.

Caveats:
- The process won't be automated

Or, during the website generation we can duplicate the content of the latest version into a new `latest/current` folder. It won't be redirects, but it'll be automated.

Caveats:
- It could impact SEO?

**Comment by thibaultCha** [comment]
@ahmadnassri @montanaflynn @thefosk @Nijikokun

**Comment by ahmadnassri** [comment]
shouldn't it be the other way around? `current` -> `x.x.x`

**Comment by ahmadnassri** [comment]
if its SEO that's the primary concern, then make the redirect pages have more meta / data in them ... (don't use the jekyll `redirect-from`)

just make ones manually and populate the redirect values from jekyll variables)

also, this would be easier if its in reverse. (`latest` to `x.x.x`)

**Comment by Nijikokun** [comment]
There isn't a plugin we can use to mitigate this?

https://github.com/nquinlan/jekyll-pageless-redirects

**Comment by ahmadnassri** [comment]
> There isn't a plugin we can use to mitigate this?

yes, but it outputs minimal HTML, and redirects using meta tags. so zero SEO.

**Comment by Nijikokun** [comment]
> yes, but it outputs minimal HTML, and redirects using meta tags. so zero SEO.

Wouldn't that actually be better? Duplicate pages are bad in Googles crawler eyes.

**Comment by ahmadnassri** [comment]
> Wouldn't that actually be better? Duplicate pages are bad in Googles crawler eyes.

ask ranking experts (i'm not one), I'm only aware of crawler behaviors and know that meta redirect pages ARE crawled, and would properly indexed if you attach proper meta data.

**Comment by ahmadnassri** [comment]
if SEO is no issue, then just use `jekyll-redirects` plugins.

but I would say reversing is still more meaningful to me.

**Comment by Nijikokun** [comment]
https://github.com/tsmango/jekyll_alias_generator/blob/master/_plugins/alias_generator.rb

Does SEO friendly redirects

**Comment by ahmadnassri** [comment]
cloudflare: minimal, but would be manual every time .. I checked, even their API doesn't support changing page rules.

**Comment by ahmadnassri** [comment]
agreement on:

> (`latest` to `x.x.x`)

?

**Comment by thibaultCha** [comment]
Yes, agreed. Actually if we use a plugin it could be automated, because the `versions.rb` plugin knows what's the latest version, so it can setup the redirects automatically (I mean create the redirect pages, assuming we are using meta tags)

**Comment by thibaultCha** [comment]
> agreement on:
> 
> (latest to x.x.x)
> ?

Actually, it would be best to do URI rewrite, so `/latest` is actually redirecting to `/x.x.x` but still shows `/latest`...

**Comment by ahmadnassri** [comment]
> Actually, it would be best to do URI rewrite, so /latest is actually redirecting to /x.x.x but still shows /latest...

sure, if you're gonna write that plugin :)

**Comment by montanaflynn** [comment]
What's the status on this? I wanted to link to quickstart but had to include the version...

**Comment by montanaflynn** [comment]
I know @Nijikokun did a redirect, can we close this issue?
