### ISSUE TITLE
Typo in plugins

### ISSUE THREAD

**Issue by tecnobrat** [Mashape/getkong.org#133]
I happened to see this commit on master and noticed a typo:

https://github.com/Mashape/getkong.org/commit/435a669c792c61b06a7ab69f6f20aeba24b00fff#diff-6a85fb7217139444aad5835f005f4058R24

`outboud` => `outbound`

**Comment by tecnobrat** [comment]
Mentioning @sinzone since they made the commit :)

**Comment by sinzone** [comment]
must have been very tired. forgot restricT too. thx @tecnobrat

**Comment by sinzone** [comment]
fixed https://github.com/Mashape/getkong.org/pull/134
