### ISSUE TITLE
should download.html be versioned

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/getkong.org#14]
Are we fine with having the link to it under: `/docs/x.x.x/download`?

**Comment by thibaultCha** [comment]
@ahmadnassri @montanaflynn @thefosk @Nijikokun

**Comment by ahmadnassri** [comment]
disagree, download.html should always point to the latest download, perhaps just add a link to "previous releases" which links back to github releases page (which acts as a nice to view & readable overview of changes and releases)

**Comment by thibaultCha** [comment]
Ok, then we don't give instructions for old installations if they change later. (Which is fine for now, I don't think it's something we need to worry about now)

(at some point we just thought it was better to version it too)

**Comment by ahmadnassri** [comment]
ideally you want people to always get the latest and greatest, so the less visible old instructions / download methods are, the better for you to have less backward maintenance & support.

**Comment by Nijikokun** [comment]
I agree with @ahmadnassri, the general solution is latest download w/ latest install guide otherwise people assume you still support older versions (LTS)

**Comment by thibaultCha** [comment]
:+1:
