### ISSUE TITLE
Documentation Error in Rate Limiting Doc

### ISSUE THREAD

**Issue by debraj-manna** [Mashape/getkong.org#145]
There is a small documentation error in the rate limiting configuration [doc](https://getkong.org/plugins/rate-limiting/#configuration) the POST call should be mentioned as below:-

```
$ curl -X POST http://kong:8001/apis/{api}/plugins \
    --data "name=rate-limiting" \
    --data "config.second=5" \
    --data "config.hour=10000"
```

The plugin name is mentioned as `ratelimiting` rather than `rate-limiting`

There is a similar mistake in the installation [doc](https://getkong.org/plugins/rate-limiting/#installation).

```
plugins_available:
  - ratelimiting
```

**Comment by debraj-manna** [comment]
Support asked me to open the bug in kong repo. So opened the [bug](https://github.com/Mashape/kong/issues/614) there & closing this one.

**Comment by ahmadnassri** [comment]
@debraj-manna you had the correct location here ... the docs are in this repo rather than the other :)

sorry for the confusion.

**Comment by ahmadnassri** [comment]
fixed.
