### ISSUE TITLE
Distribution Packages

### ISSUE THREAD

**Issue by thefosk** [Mashape/getkong.org#15]
Kong will be released with the following supported distributions:

- [x] Amazon Linux AMI (.rpm) **@thefosk**
- [x] CentOS 5/6/7 (rpm) **@thefosk**
- [x] Debian 6/7 (.deb) **@thefosk**
- [x] Ubuntu 12.04/14.04 (.deb) **@thefosk**
- [x] OS X 
  - [x] pkg **@thefosk**
  - [x] [homebrew](thibaultcha/homebrew-kong) @thibaultcha 
  - [ ] [script](https://gist.github.com/Nijikokun/189f84226f092dccd359) @Nijikokun 
- [x] Other

**Comment by thibaultCha** [comment]
No "raw"?

**Comment by thibaultCha** [comment]
I updated the releases with checkboxes for what is done (we need to consider what is documented, aka written on [getkong.org/downloads]. And added the Mac OS install script written by @Nijikokun

**Comment by thefosk** [comment]
Added "raw" (alias "Other")

**Comment by thibaultCha** [comment]
:+1:

**Comment by ahmadnassri** [comment]
shouldn't this be on [Mashape/Kong](https://github.com/Mashape/kong) ?

**Comment by ahmadnassri** [comment]
one point to add here, is that builds should work on travis and upload to Github Releases as release assets.

**Comment by thibaultCha** [comment]
Don't think it's necessary for a beta. I think it's a better issue here than on Kong. It's docs.

**Comment by thibaultCha** [comment]
First launch*

**Comment by ahmadnassri** [comment]
> Don't think it's necessary for a beta.

sure, can be manual for now and automated later, just wanted to capture it in an issue/comment so we can track.

**Comment by thefosk** [comment]
So we do have `rpm`, `deb` and `pkg`. I need to create test cases and then we can update this issue.
