### ISSUE TITLE
Conf.yml or Kong.yml

### ISSUE THREAD

**Issue by orliesaurus** [Mashape/getkong.org#16]
Should it be 
```
kong start -c /path/to/conf.yml
```

or what I think

```
kong start -c /path/to/kong.yml
```
based on the first line referring to kong.yml not conf.yml

http://getkong.org/docs/0.1.1beta-2/getting-started/configuration/

P.s. it's the little things ;)

**Comment by Nijikokun** [comment]
`/etc/kong/conf.yml` makes more sense than `/etc/kong/kong.yml`

**Comment by ahmadnassri** [comment]
if keeping with nginx style: `/etc/nginx/nginx.conf` then it should be `/etc/kong/kong.yml`

**Comment by SGrondin** [comment]
I agree with @ahmadnassri and @orliesaurus

**Comment by thibaultCha** [comment]
Which is why it's currently kong.yml.

**Comment by thibaultCha** [comment]
Should already be fixed if the docs were rewritten but keeping it open just in case.

**Comment by ahmadnassri** [comment]
it is now.
