### ISSUE TITLE
Freature req: Bulk create apis

### ISSUE THREAD

**Issue by gebrits** [Mashape/getkong.org#162]
Consider a multitenant environment where each new tenant requires configuring a couple of apis, all based on a fixed scheme. 

It would be great if there was a bulk POST option to create multiple apis (in above example for 1 new tenant) at the same time. 

Thoughts?

**Comment by davecozens** [comment]
In an ideal world, when importing, if ID values are included in the config they should be updated if existing or inserted with same ID if not.

**Comment by gavinlove** [comment]
Sounds like a good case for [Kongfig](https://github.com/mybuilder/kongfig) we do exactly this using puppet add one line for each tenant with their domain and then it does everything for us

**Comment by thibaultcha** [comment]
Closing this as it is related to Kong itself and not the website. Such a feature is already requested there, too.
