### ISSUE TITLE
add: Cloud page 

### ISSUE THREAD

**Issue by sinzone** [Mashape/getkong.org#164]
next to enterprise - simple form for gather kong cloud interest and show the world that we DO have a kong cloud pilot program. can also just redirect to demo form for now

**Comment by theetrain** [comment]
From #232 
![image](https://cloud.githubusercontent.com/assets/12798751/15733039/33f11132-2850-11e6-984b-9335d9c0fe4b.png)

**Comment by ahmadnassri** [comment]
closing in favor of #232
