### ISSUE TITLE
Add Sidecar Gitter chat to Kong website

### ISSUE THREAD

**Issue by sinzone** [Mashape/getkong.org#176]
https://sidecar.gitter.im/

**Comment by sinzone** [comment]
can be chat.getkong.org or getkong.org/chat

**Comment by ahmadnassri** [comment]
wat? no the sidecar thing is an overlay on the website just like intercom ... it doesn't get its own domain

**Comment by ahmadnassri** [comment]
closing this issue unless the need arises again
