### ISSUE TITLE
Optional final slash in admin endpoints 

### ISSUE THREAD

**Issue by thefosk** [Mashape/getkong.org#19]
By appending the `-L` argument to every curl command.

**Comment by ahmadnassri** [comment]
EVERY command? seems excessive, should only be for internal API calls that need it.

**Comment by thibaultCha** [comment]
Just for the trailing slash? I would rather add a trailing slash...

**Comment by ahmadnassri** [comment]
agreed with @thibaultcha

**Comment by thefosk** [comment]
This has been fixed in a separate branch that will be merged into master

**Comment by thibaultCha** [comment]
What was fixed? How? What was the problem?

**Comment by thefosk** [comment]
The trailing slash problem, by simply duplicating the endpoints since Lapis doesn't support regex-matching in routes.

**Comment by thibaultCha** [comment]
This might seem like a solution but since every other plugin will force people to use tralling slash, I think it is going to create **inconsistencies**. I would rather have a trailing slash **always** mandatory, than having it optional on some endpoints (where the endpoint is duplicated) and not there on other endpoints (when the developer did not implement a duplicated endpoint)

**Comment by thefosk** [comment]
I wanted to do that too, but @Nijikokun @SGrondin and @montanaflynn really liked having supports for routes with and without a final slash, and without any redirect, so that's why I introduced it. The only thing is that we are duplicating routes, and as you said it could lead to inconsistencies in the future, although inconsistencies could be fixed by not allowing plugins to create routes using the Lapis `app` object, but an intermediate function, like:

```lua
add_get_route("/hello/world", function(self)
  -- Do something
end)
```

and `add_get_route` basically just replicates the embedded function in:

```lua
function add_get_route(route, cb)
  app.get(route, cb)
  app.get(route.."/", cb)
end
```

This could be an option that will mitigate the inconsistencies until Lapis introduces better support for optional slashes.

**Comment by montanaflynn** [comment]
>..., and without any redirect, ...

I only said that `POST /apis` should work. A 301 redirect would be fine with me.

**Comment by thefosk** [comment]
Redirects are not automatically followed by curl, so for example if making a request to `POST /apis/` returns a `301` redirect to `/apis`, curl will not automatically follow it and nothing will happen unless the `-L` parameter is provided, so that's why this issue was originally labeled as: "Using -L in every curl command".

To just make every request work without additional curl arguments on, for example, both `/apis/` and `/apis`, the systems needs to explicitly define both routes.

**Comment by montanaflynn** [comment]
Thanks for clearing that up for me, I didn't know the reasoning behind adding curl's -L "Follow Redirects" flag and missed all the discussion between you @SGrondin and @Nijikokun. 

On one hand I would prefer them to both "just work" but on the other I think adding a body with the error "missing trailing slash" is enough to avoid any confusion, especially if the solution's implementation adds technical debt and inconsistencies as @thibaultCha described.

**Comment by Nijikokun** [comment]
https://github.com/leafo/lapis/blob/master/lapis/application.lua#L339

Lapis supports a `default_route` on the router which would allow you to make them "just work" rather than a redirect.

A redirect is fine, I don't think that makes curl commands require a `-L`

**Comment by thefosk** [comment]
The `default_route` is what I was adopting which triggers the redirect. Curl doesn't follow redirects by default unless the `-L` argument has been set. 

A redirect it's just a regular HTTP response with a `301` status code and a `Location` header telling the client where the new location is. Curl doesn't do any magic unless told so.

**Comment by thefosk** [comment]
This has been closed by implementing https://github.com/leafo/lapis/issues/276 which basically allows us to have the same behavior without redirects and `-L` arguments on curl.
