### ISSUE TITLE
update list of companies using Kong

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/getkong.org#192]
- [Sidecar](https://hello.getsidecar.com/)
- Curaytor
- Teamchat
- iGola
- BuzzLogix
- Conde Nast
- Care Otter
- The Guardian
- MorphoTrust
- Aquilent
- Eurostar
- The University of Auckland
- DataBC

**Comment by daviesf1** [comment]
Curaytor, Teamchat, iGola, BuzzLogix, Conde Nast, Care Otter, The Guardian, MorphoTrust, Aquilent, Eurostar, The University of Auckland, DataBC

**Comment by ahmadnassri** [comment]
@nikz you can grab logos & short description from linkedin for each of those.

**Comment by daviesf1** [comment]
add Newton Circus

**Comment by lconnolly** [comment]
@ahmadnassri @daviesf1 is this meant to *replace* the list currently on GetKong.org? Or append to it?

Also, should I order these in any particular fashion? Alphabetical?

**Comment by daviesf1** [comment]
Don't add Newton Circus yet - they still haven't signed the agreement

**Comment by ahmadnassri** [comment]
@lconnolly append, alphabetical.

**Comment by lconnolly** [comment]
OK, this is the merged list, in alphabetical order: ... gathering logos now.

- Aquilent
- BuzzLogix
- Care Otter
- Conde Nast
- Curaytor
- DataBC
- Eurostar
- Flyer, Inc.
- Gengo
- Grow Remote
- iGola
- Indix
- Mashape Marketplace
- Mavi
- MorphoTrust
- Newton Circus
- Parlor Inc.
- Sidecar
- Springer
- Teamchat
- The Guardian
- The University of Auckland
- Unified Compliance

**Comment by daviesf1** [comment]
I'd remove iGola and Newton Circus.

**Comment by ahmadnassri** [comment]
keep Mashape Marketplace on top.

**Comment by lconnolly** [comment]
Roger. Updated:

- *Mashape Marketplace*
- Aquilent
- BuzzLogix
- Care Otter
- Conde Nast
- Curaytor
- DataBC
- Eurostar
- Flyer, Inc.
- Gengo
- Grow Remote
- Indix
- Mavi
- MorphoTrust
- Parlor Inc.
- Sidecar
- Springer
- Teamchat
- The Guardian
- The University of Auckland
- Unified Compliance

**Comment by sinzone** [comment]
![a6d747d4-7a92-483a-8ae7-6ff48d6ff843](https://cloud.githubusercontent.com/assets/1213643/15697746/0452e218-2772-11e6-9a86-767b7ccc001d.png)

**Comment by theetrain** [comment]
New company page has been deployed.
