### ISSUE TITLE
code snippets

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/getkong.org#22]
two questions:

- should we standardize spacing? (e.g. some JSON snippets have 4 spaces, curl have 2)
- do we really need a dollar sign for bash snippets? makes it more annoying to copy-paste.

**Comment by montanaflynn** [comment]
and some [multi-line curl snippets](http://getkong.org/docs/0.1.1beta-2/getting-started/adding-your-api/#add-your-api-using-the-restful-api) are missing backslashes so they cannot be copy-pasted

![screen shot 2015-04-20 at 1 37 22 pm](https://cloud.githubusercontent.com/assets/24260/7239965/95069580-e762-11e4-89db-8487a30bbac3.png)

**Comment by thibaultCha** [comment]
And what about the style? A dark theme would be nice:

![ckayo5xcd5swgxljlihdc-ksohbvds0arauaq0kfog8](https://cloud.githubusercontent.com/assets/1125431/7240049/9d8ab5c8-e7ae-11e4-9e5b-386240475baa.png)

But even nicer would be to properly style the inline <code> blocks:

![screenshot 2015-04-20 22 00 34](https://cloud.githubusercontent.com/assets/1125431/7240052/a06264ee-e7ae-11e4-8be6-ce8bfe0e64f0.png)

**Comment by thibaultCha** [comment]
> do we really need a dollar sign for bash snippets?

I like it better with a dollar sign. It just means it's a command we are inviting you to execute and is easy to spot when quickly reading a guide.

**Comment by Nijikokun** [comment]
`4` for cURL requests

```bash
$ curl -X POST http://example.org
    --data "and=some"
    --data "some=data"
```

**Comment by Nijikokun** [comment]
> But even nicer would be to properly style the inline <code> blocks:

Me and jitachi went over numerous colorings / styles, and have deduced that the red style stands out the most without appearing like a link (blue) or giving the page a dull look (grey), and without hurting eyes (green, yellow), the only alternative would be an orange or purple, but since we already have red we stuck with red.

**Comment by ahmadnassri** [comment]
:-1: for rules as outlined by @nijikokun let's apply those and stick to them

**Comment by thibaultCha** [comment]
> its not as important as content at the moment

Obviously. Only a suggestion.

**Comment by ahmadnassri** [comment]
if nobody else is already on it, I can assign to myself and start cleaning up.

**Comment by Nijikokun** [comment]
> if nobody else is already on it, I can assign to myself and start cleaning up.

That would help out a lot, I'm currently cleaning up plugins.

**Comment by montanaflynn** [comment]
Niji in your code example with backslashes remove:

```shell
$ curl -X POST http://example.org
    --data "and=some"
    --data "some=data"
```

when I copy and paste that I get: `zsh: command not found: --data`

**Comment by thibaultCha** [comment]
Well you do need backslashes, there's no way around it

**Comment by Nijikokun** [comment]
> Niji in your code example with backslashes removed:

was just an example, but for you I will fix it :heart:

**Comment by sinzone** [comment]
@Nijikokun you think green was hurting eyes more than red?

**Comment by Nijikokun** [comment]
Yes

**Comment by thibaultCha** [comment]
I can totally see that. But #36 has a smaller padding and a new font, which looks better, so consider it.

**Comment by Nijikokun** [comment]
It looks good :+1:
