### ISSUE TITLE
extra html escaping in data attributes on render

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/getkong.org#23]
this will break any tracking events.

```html
<a href="/download" class="button" data-analytics="{&quot;event&quot;: &quot;Clicked download&quot;, &quot;type&quot;: &quot;button&quot;, &quot;location&quot;: &quot;header&quot;}">Download</a>
```

**Comment by Nijikokun** [comment]
line? I never escaped anything.

**Comment by ahmadnassri** [comment]
the escaping is on render.

I'm thinking its related to the redcapet config ... not sure who set that up, assumed it was you, this particular example is on [app/index.html#L69](https://github.com/Mashape/getkong.org/blob/master/app/index.html#L69)

**Comment by Nijikokun** [comment]
yeah, one thing is to just inject it via javascript instead of in the html.

**Comment by Nijikokun** [comment]
This has been fixed, and deployed.
