### ISSUE TITLE
update our gitter from simple link to sidecar (open in app) - can keep the icon.

### ISSUE THREAD

**Issue by sinzone** [Mashape/getkong.org#246]
![](http://cl.ly/012I0V1N0f2a/Image%202016-06-23%20at%201.13.17%20AM.png)

https://sidecar.gitter.im/

example:https://www.cockroachlabs.com/docs/install-cockroachdb.html

**Comment by ahmadnassri** [comment]
don't think we can easily keep the icon ..

**Comment by theetrain** [comment]
Do you want something like this?

### 1) Hover then click Gitter button

![20160623 gitter](https://cloud.githubusercontent.com/assets/12798751/16326644/6cea0f14-3996-11e6-96b2-2d4ac5c45349.gif)


### 2) Sidecar opens, and Gitter icon becomes 'X'

![20160623 gitter](https://cloud.githubusercontent.com/assets/12798751/16326649/868ec298-3996-11e6-8634-3732df5efebe.png)

**Comment by sinzone** [comment]
that perfect.

1) on mouse over not gitter txt but "chat with kong community"

2) yup.

**Comment by sinzone** [comment]
thank you.
