### ISSUE TITLE
nginx.conf template in install docs is not properly escaped >= v0.6

### ISSUE THREAD

**Issue by rowanthorpe** [Mashape/getkong.org#254]
Having followed the install-from-source docs for Kong v0.8 I copy-pasted the appropriate parts from the configuration page (corresponding to `app/docs/0.x.x/configuration.md`) but when attempting to start kong errors-out, as vital parts are missing. Looking at configuration.md in the repo up to version 0.5 I see some quite ungainly but obviously necessary parser-escaping for the `{{ xx }}` and `$xx` values (possibly to withstand markdown parsing within whatever-generates-the-site parsing?). For example:
```yaml
...
    lua_shared_dict cache {{ "{{memory_cache_size" }}}}m;
...
```
...and the corresponding pages on the website do ultimately render those parts correctly. From v0.6 onwards though the escaping-syntax is missing e.g.:
```yaml
    lua_shared_dict cache {{memory_cache_size}}m;
```
...and the corresponding values are entirely missing on their pages on the website.

**Comment by thibaultcha** [comment]
Thanks for the report, sorry for the delay.
