### ISSUE TITLE
nginx.conf template in install docs has an alignment typo >= v0.6

### ISSUE THREAD

**Issue by rowanthorpe** [Mashape/getkong.org#255]
Up to version 0.5 the beginning of the embedded nginx.conf at `app/docs/0.5.x/configuration.md` looks like this:

```yaml
nginx: |
  worker_processes auto;
  error_log logs/error.log error;
  daemon on;
   ...
```
...and from 0.6.x onwards it looks like this:
```yaml
nginx: |
worker_processes auto;
  error_log logs/error.log error;
  daemon on;
```
...note the misaligned worker_processes line in the latter version which causes a yaml-parsing error when starting kong.

**Comment by thibaultcha** [comment]
Thanks, just fixed and deployed.
