### ISSUE TITLE
Cassandra dependency

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/getkong.org#38]
The current location is easy to skip over and miss at first glance. 

Right now we have dependencies listed as step one for "Other" which is where I would expect Casandra to be mentioned as well. We also mention that Cassandra must be running in the "Start Kong" section for all distributions except for Docker but I feel it should be clear it's a dependency before you get there.

![screen shot 2015-04-21 at 4 35 07 pm](https://cloud.githubusercontent.com/assets/24260/7264820/4fc08a56-e845-11e4-93ca-70e50c182c8c.png)

**Comment by ahmadnassri** [comment]
this has been addressed a while ago
