### ISSUE TITLE
SNI Object routes sidebar doesn't link to corresponding section

### ISSUE THREAD

**Issue by chrisjoywebb** [Mashape/getkong.org#396]
The *SNI Object routes* link in the sidebar of https://getkong.org/docs/ does not link to the SNI Objects section of the docs.

<img width="1355" alt="screen shot 2017-04-24 at 14 21 01" src="https://cloud.githubusercontent.com/assets/6216666/25359259/54f7e48c-28f9-11e7-995b-696109b8b5f3.png">

**Comment by Tieske** [comment]
@chrisjoywebb can't reproduce this, seems fixed.

**Comment by Tieske** [comment]
indeed, see https://github.com/Mashape/getkong.org/pull/397/files
