### ISSUE TITLE
Adding api doesn't work

### ISSUE THREAD

**Issue by jithuatwork** [Mashape/getkong.org#402]
I have an API server running at http://localhost:3000

I have the following routes http://localhost:3000/jithu

Now I added the API
curl -i -X POST http://localhost:8001/apis/   -d 'name=example' -d 'upstream_url=http://localhost:3000' -d 'hosts=localhost' -d 'methods=GET,HEAD,POST,DELETE'

Now when I try this,
curl -i -X GET --url http://localhost:8000/jithu --header 'Host: localhost'
HTTP/1.1 404 Not Found
Date: Wed, 26 Apr 2017 06:02:14 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: kong/0.10.1

{"message":"no API found with those values"}

Any help will be appreciated.

**Comment by coopr** [comment]
This repo is for the GetKong.org website - not for the Kong API gateway.

Please have a look at https://github.com/Mashape/kong - you may want to ask via the mailing list or Gitter chat noted on that repo.
