### ISSUE TITLE
Footer for Newsletter signup should appear on all pages, not just homepage

### ISSUE THREAD

**Issue by christinang89** [Mashape/getkong.org#41]
Right now the footer is only shown on the homepage, please include it in all the pages, especially download/ install page.

![screen shot 2015-04-23 at 3 04 25 pm](https://cloud.githubusercontent.com/assets/5797207/7308519/1088fb26-e9ca-11e4-8bda-be552e4b6966.png)

**Comment by Nijikokun** [comment]
The title could use rewording as well

**Comment by Nijikokun** [comment]
Fixed in master.
