### ISSUE TITLE
UUOC-X (unnecessary use of curl -X)

### ISSUE THREAD

**Issue by hydrargyrum** [Mashape/getkong.org#447]
The site getkong.org is riddled with "curl -X GET" and "curl -X POST" occurrences, which are deemed "unnecessary" by the curl author himself (at best, harmful at worst): https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/

The documentation could be fixed by simply removing "-X GET" and "-X POST" in curl samples.

**Comment by thibaultcha** [comment]
Arguably, in the case of a documentation like getkong.org, explicitly specifying the HTTP method has the benefit of self-documenting the API and the HTTP methods are accepted by each of the documented endpoints, and helps the reader (familiar or not with curl, btw) understanding the requests being made and helps following the examples.

**Comment by hydrargyrum** [comment]
I think most readers would assume that without arguments specifying a body to post, the request must necessarily be a GET, and with arguments specifying "--data", the request should most likely be POST (or PUT, there could be some ambiguity, that's right).
But I see what you mean, for documentation, one can be explicit to avoid ambiguity.
