### ISSUE TITLE
Admin API is not RESTful

### ISSUE THREAD

**Issue by XVincentX** [Mashape/getkong.org#457]
Hello guys; I'm using Kong and I think it's a great product. Please keep going the great work!

![image](https://user-images.githubusercontent.com/1416224/28405869-7bdb44f8-6d2e-11e7-9563-48435827029c.png)

There are multiple places in this website where it's stated that Kong Admin API is a REST API, although it is not.

In particular, it is not respecting the principle of uniform interface through an hypermedia format (such as hal+json, siren and so on).

I'm not sure how much is important to you guys, but it broke my expectations (multiple times); I then figured out it was not a real REST API.

**Comment by p0pr0ck5** [comment]
I think the [mailing list](https://groups.google.com/forum/#!forum/konglayer) or [Gitter](https://gitter.im/Mashape/kong) would be the better forum for this discussion. Thanks for checking out Kong! :D

**Comment by XVincentX** [comment]
Alright - thanks for the super prompt reply!
