### ISSUE TITLE
Better 404 page

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/getkong.org#49]
Let's discuss how we can improve the 404 page.

![screen shot 2015-04-25 at 3 13 03 pm](https://cloud.githubusercontent.com/assets/24260/7335701/7ff56542-eb84-11e4-84a3-4fc2eb242e51.png)

**Comment by Nijikokun** [comment]
- **Go back** instead of homepage using window history.
- A better title than **D'oh** maybe something witty and funny from the **King Kong** movie or **Kong** related.

**Comment by christinang89** [comment]
@rainum for now, let's just do:
Sorry, the page you're looking for is not here. 

* Go back to our [homepage](http://getkong.org) and try again
* Browse our [documentation](http://getkong.org/docs/) or [installation instructions](http://getkong.org/download/) to get started
* Check out our [community page] (http://getkong.org/community/) for support or to report an issue.
