### ISSUE TITLE
Kong 0.11 support for TLSv1

### ISSUE THREAD

**Issue by amramtamir** [Mashape/getkong.org#530]
Hi,
I am in the process of upgrading to 0.11 and I need to support TLSv1.
I saw that in the ssl_ciphers there is an option to choose from a predefined list (old) for example which add the SSL CIPHERS for TLSv1, but the issue is that the ssl_protocols is configured to only accept TLS connections from TLSv1.2 and TLSv1.1.
Haven't found how to change it via configurations.

Thanks!

**Comment by p0pr0ck5** [comment]
Hi,

Please don't cross post to github and gitter. You can use a custom Nginx template to define a different `ssl_protocols` directive if you so desire: https://getkong.org/docs/0.11.x/configuration/#custom-nginx-configuration-embedding-kong

**Comment by amramtamir** [comment]
Hi,
Thanks, I have managed to pull this off by using a custom template.
