### ISSUE TITLE
"You are browsing an outdated version of the documentation"

### ISSUE THREAD

**Issue by thibaultCha** [Mashape/getkong.org#61]
Display a warning on top of every doc page when the user is not seeing the most recent version of the documentation. Include a link to the most recent version.

![screenshot 2015-04-30 15 29 55](https://cloud.githubusercontent.com/assets/1125431/7413683/0ba16902-ef4e-11e4-976c-ee5308043b46.png)

@jitachi Do you have guidelines or a mockup to implement this? Thanks

**Comment by ahmadnassri** [comment]
we already have the yellow alert box, makes sense to use here.

**Comment by thibaultCha** [comment]
I feel like the warning should be stronger.

**Comment by ahmadnassri** [comment]
like a red-ish color?

sure, maybe. the rest of the style of the alert box works as is though.

**Comment by thibaultCha** [comment]
We'll see when we'll implement it when we'll have another version out
