### ISSUE TITLE
Misaligned bullet-points in UL in Firefox

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/getkong.org#66]
Screenshot taken from: http://getkong.org/docs/0.2.0-2/about/what/

![screen shot 2015-05-06 at 9 10 47 am](https://cloud.githubusercontent.com/assets/24260/7497515/d6fe54e0-f3cf-11e4-8ef0-b95253c69d9f.png)

**Comment by rainum** [comment]
14 years :laughing: https://bugzilla.mozilla.org/show_bug.cgi?id=36854
