### ISSUE TITLE
create a "requirements" page

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/getkong.org#72]
- to list all required packages for installations across different distribution methods.
- to link from the download page with the text: "check all your dependencies are met, click here for a full list of requirements."

**NOTE** this is turning into an install debugging thread, i'll list everything here then separate out into individual tickets as applicable, for now using this as a draft space.

-  `sudo` is a requirement for `kong.postinst` but it probably shouldn't be, we can use "su" which comes pre-installed with most distros anyways, can use `su -c ‘command’`

**Comment by Nijikokun** [comment]
What do you think about directly mentioning requirements on the installation page rather than a link to a secondary page that could be overlooked?

**Comment by ahmadnassri** [comment]
that would work as well ... i'm going through all the different distros now and gonna list all the requirements I find ... if the list becomes too big, a separate page might be cleaner ... if only a few, then within the download/install page should be fine ...

also for things like debian / ubuntu different versions would potentially require different requirements ... again will go through them all today and see how big the list might get.
