### ISSUE TITLE
guide states adding a plugin to config, that's already added

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/getkong.org#73]
guide suggests [adding a plugin](http://getkong.org/docs/0.2.0-2/getting-started/enabling-plugins/): `Add keyauth under the plugins_available property in your Kong instance configuration file`

however, it seems all plugins are already added and enabled by default.

**Comment by thibaultCha** [comment]
It's adding a plugin on an API, not on Kong.

**Comment by ahmadnassri** [comment]
that's not what the text suggests.

**Comment by thibaultCha** [comment]
Because for now all of them are enabled by default, might not be the case when we have a proper architecture. Otherwise idk, didn't write this.

**Comment by thibaultCha** [comment]
And I think it's really fine, it makes people discover this property and know what it is used for.

**Comment by Nijikokun** [comment]
The original text stated this, so I kept it, even though they are enabled by default the text allows you to understand where you will place third-party plugins or plugins that are not enabled by default should you come to a point where the plugin is not being invoked or ran at all.

**Comment by ahmadnassri** [comment]
yeah, I don't think its a "problem" per say ... perhaps an adjustment of the text, an inexperienced user would potentially be confused to why the instructions are guiding him/her to do something that's already done ...

**Comment by Nijikokun** [comment]
```
Add keyauth ... should it not already exist
```

**Comment by ahmadnassri** [comment]
:+1:
