### ISSUE TITLE
[guide] Document how the Proxy Layer API (8000) works.

### ISSUE THREAD

**Issue by Nijikokun** [Mashape/getkong.org#80]
Some users have been emailing with confusion surrounding the workings of the Proxy Layer API which resides on port `8000`

Perhaps a page where it is explained in detail, what headers are required *(even if only one)*, what features it supports, and the likes would cure the situation we currently face.

As it stands of now there are only glimpses into how it works:

http://getkong.org/docs/0.2.1/getting-started/adding-your-api/

**Comment by sinzone** [comment]
![] (https://i.imgur.com/j8jYI0X.png)

**Comment by ahmadnassri** [comment]
agreed.

**Comment by sinzone** [comment]
+1 @Nijikokun
