### ISSUE TITLE
implicit description of how to use DNS with Kong in production

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/getkong.org#87]
it occurred to me *(from customer feedback)* that the usage of `Host` header in examples are causing some confusion for people.

basically, its empowering the assumption that you need to call the proxy address directly and pass a `Host` header, where in a real-world implementation, you should be able to point any DNS address (domain / subdomain) to your proxy network address and no longer require passing of a `Host` header in your HTTP request.

this is not an obvious conclusion from following the tutorial and reading the docs, and it does count as a bit of an advanced knowledge for some developers.

**suggestion:** add a "deploying to production" section in the tutorial (at the end) that describes this as well as any related considerations when going to production.

**Comment by montanaflynn** [comment]
Here's a rough draft for the content: https://gist.github.com/montanaflynn/a3a9336384d42188a45e

Also to be potentially included (perhaps as separate sections?)

- Firewall for admin API
- Server Configuration (ulimit, etc...)

**Comment by thibaultCha** [comment]
Is this somehow related to #80? Basically just documenting how proxying works?

**Comment by montanaflynn** [comment]
Yes it is related. I think this was specific to "production" where #80 is a general overview of Kong's proxy.

**Comment by thibaultCha** [comment]
Then it should probably go like this:

- Explain how to add an API to Kong ("notice we're using port 8001, the Admin API)
- Add an API with a `public_dns` and a `path`
- Show how to make a request with a `Host` header
- Show that `X-Host-Override` also works ("check this out if you care using it from a browser and can't use the Host header")
- Request using the path ("check this out if you want to query an API by path")
- Request using the path + `strip_path` option

**Comment by Nijikokun** [comment]
#80 encompasses the entirety of the proxy layer, that includes any *production* related sections.
