### ISSUE TITLE
CASSANDRA Section in the Docs

### ISSUE THREAD

**Issue by sinzone** [Mashape/getkong.org#96]
- [ ] Why Cassandra
- [ ] How to install Cassandra
- [ ] How to scale Cassandra

**Comment by sinzone** [comment]
should be not long. Short, simple and straight to the point.

**Comment by sinzone** [comment]
to check #84

**Comment by thibaultCha** [comment]
Closing in favour of #64. They are really the same thing. A guide about Cassandra.
